server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: produit-service
          uri: lb:http://PRODUIT-SERVICE
          predicates:
            - Path=/api/v1/produits/**

        - id: commandes-service
          uri: lb:http://COMMANDES-SERVICE
          predicates:
            - Path=/api/v1/commandes/**


        - id: notification-service
          uri: lb:http://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notification/**


